// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionPrestamosPersonales2023.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("Ocupaciones", b =>
                {
                    b.Property<int>("OcupacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("salario")
                        .HasColumnType("REAL");

                    b.HasKey("OcupacionId");

                    b.ToTable("Ocupaciones");
                });

            modelBuilder.Entity("Pagos", b =>
                {
                    b.Property<int>("PagosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Concepto")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Fecha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Monto")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PersonaId")
                        .HasColumnType("TEXT");

                    b.HasKey("PagosId");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("PagosDetalle", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PagoId")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("prestamosid")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("valorPagado")
                        .HasColumnType("REAL");

                    b.HasKey("id");

                    b.ToTable("PagosDetalle");
                });

            modelBuilder.Entity("Persona", b =>
                {
                    b.Property<int>("PersonaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("balance")
                        .HasColumnType("REAL");

                    b.Property<string>("direccion")
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("nacimiento")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ocupacionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("telefono")
                        .HasColumnType("TEXT");

                    b.HasKey("PersonaId");

                    b.ToTable("Persona");
                });

            modelBuilder.Entity("Prestamos", b =>
                {
                    b.Property<int>("PrestamosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("balance")
                        .HasColumnType("INTEGER");

                    b.Property<string>("concepto")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("fecha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("monto")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("personaid")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("vence")
                        .HasColumnType("TEXT");

                    b.HasKey("PrestamosId");

                    b.ToTable("Prestamos");
                });
#pragma warning restore 612, 618
        }
    }
}
